export const SAVE_PICTURE = 'SAVE_PICTURE'
export const DELETE_PICTURE = 'DELETE_PICTURE'
export const DELETE_ALL_PICTURES = 'DELETE_ALL_PICTURES'
export const SAVE_LIST_FAVORITE_PICTURES = 'SAVE_LIST_FAVORITE_PICTURES'
